FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

RUN addgroup -S vikram && adduser -S -G vikram vikram

COPY $TARGETPLATFORM/vikram /usr/local/bin/vikram

RUN mkdir -p /home/vikram && chown -R vikram:vikram /home/vikram

USER vikram

ENTRYPOINT ["vikram"]
CMD ["gateway"]
